const functions = require('firebase-functions');
const ssr = require('./ssr.js') // Generated by adapter-firebase-function

exports.ssr = functions.https.onRequest(async (request, response) => {
	return await ssr(request,response)
});